const express = require("express");
const path = require("path");

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

function buildPages({ template, idea }) {
  const baseTitle =
    template === "gaming" ? "Gaming Website" :
    template === "business" ? "Business Website" :
    template === "portfolio" ? "Portfolio" :
    template === "startup" ? "Startup Landing" :
    template === "store" ? "Online Store" :
    idea ? idea :
    "My Website";

  const nav = `
    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="about.html">About</a>
      <a href="contact.html">Contact</a>
    </nav>
  `;

  const footer = `
    <footer style="margin-top:40px; padding:20px; text-align:center; color:#94a3b8;">
      Contact: jd@example.com
    </footer>
  `;

  const styleCss = `
    body { margin:0; font-family:Arial; background:#0f172a; color:white; }
    .nav a { margin-right:15px; color:#22d3ee; text-decoration:none; }
    .card { padding:20px; background:#1e293b; border:1px solid #22d3ee; border-radius:10px; }
  `;

  const indexHtml = `
    <html><head><title>${baseTitle}</title><link rel="stylesheet" href="style.css"></head>
    <body>
      ${nav}
      <div class="card">
        <h1>${baseTitle}</h1>
        <p>This is the home page for ${baseTitle}.</p>
        <p>Generated by your AI Website Generator.</p>
      </div>
      ${footer}
    </body></html>
  `;

  const aboutHtml = `
    <html><head><title>About - ${baseTitle}</title><link rel="stylesheet" href="style.css"></head>
    <body>
      ${nav}
      <div class="card">
        <h1>About</h1>
        <p>About page for ${baseTitle}.</p>
      </div>
      ${footer}
    </body></html>
  `;

  const contactHtml = `
    <html><head><title>Contact - ${baseTitle}</title><link rel="stylesheet" href="style.css"></head>
    <body>
      ${nav}
      <div class="card">
        <h1>Contact</h1>
        <p>Email: jd@example.com</p>
      </div>
      ${footer}
    </body></html>
  `;

  return {
    "index.html": indexHtml,
    "about.html": aboutHtml,
    "contact.html": contactHtml,
    "style.css": styleCss
  };
}

app.post("/generate-site", (req, res) => {
  const { template, idea } = req.body || {};
  const pages = buildPages({ template, idea });
  res.json({ pages });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Running on port " + PORT));
