import express from "express";
import path from "path";
import { fileURLToPath } from "url";

const app = express();
app.use(express.json());

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

app.use(express.static(path.join(__dirname, "public")));

function buildPages({ template, idea }) {
  const baseTitle =
    template === "gaming" ? "My Gaming Site" :
    template === "business" ? "Zeiter Marketing" :
    template === "portfolio" ? "My Portfolio" :
    template === "startup" ? "LaunchPad" :
    template === "store" ? "Neon Store" :
    idea ? idea :
    "My Website";

  const nav = `
    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="about.html">About</a>
      <a href="contact.html">Contact</a>
    </nav>
  `;

  const footer = `
    <footer style="margin-top:40px; padding:20px; text-align:center; color:#94a3b8; font-size:14px; opacity:0.8;">
      Contact: jdz@example.com
    </footer>
  `;

  const styleCss = `
    body {
      margin: 0;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Inter", sans-serif;
      background: #020617;
      color: #e5e7eb;
    }
    .shell {
      max-width: 900px;
      margin: 0 auto;
      padding: 32px 20px 60px;
    }
    .nav {
      display: flex;
      gap: 16px;
      margin-bottom: 24px;
    }
    .nav a {
      color: #a5f3fc;
      text-decoration: none;
      font-size: 14px;
    }
    .nav a:hover {
      text-decoration: underline;
    }
    h1 {
      font-size: 32px;
      color: #22d3ee;
      text-shadow: 0 0 16px rgba(34, 211, 238, 0.75);
      margin-bottom: 8px;
    }
    h2 {
      margin-top: 24px;
      color: #a5f3fc;
    }
    .card {
      margin-top: 18px;
      padding: 18px 20px;
      border-radius: 14px;
      border: 1px solid rgba(34, 211, 238, 0.3);
      background: rgba(15, 23, 42, 0.9);
    }
    .btn {
      display: inline-block;
      margin-top: 16px;
      padding: 10px 18px;
      border-radius: 999px;
      background: linear-gradient(135deg, #22d3ee, #6366f1);
      font-weight: 600;
      color: #020617;
      text-decoration: none;
      font-size: 14px;
    }
  `;

  const indexHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${baseTitle}</title>
      <link rel="stylesheet" href="style.css">
    </head>
    <body>
      <div class="shell">
        ${nav}
        <h1>${baseTitle}</h1>
        <div class="card">
          <h2>Welcome</h2>
          <p>This is the home page for ${baseTitle}.</p>
          <p>Generated by your AI Website Generator.</p>
          <a href="contact.html" class="btn">Get in touch</a>
        </div>
      </div>
      ${footer}
    </body>
    </html>
  `;

  const aboutHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>About - ${baseTitle}</title>
      <link rel="stylesheet" href="style.css">
    </head>
    <body>
      <div class="shell">
        ${nav}
        <h1>About</h1>
        <div class="card">
          <p>${baseTitle} is a website generated from a single idea or template.</p>
          <p>Customize this page to tell your story, mission, and background.</p>
        </div>
      </div>
      ${footer}
    </body>
    </html>
  `;

  const contactHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Contact - ${baseTitle}</title>
      <link rel="stylesheet" href="style.css">
    </head>
    <body>
      <div class="shell">
        ${nav}
        <h1>Contact</h1>
        <div class="card">
          <p>Drop your contact details here.</p>
          <p>Email: you@example.com</p>
        </div>
      </div>
      ${footer}
    </body>
    </html>
  `;

  return {
    "index.html": indexHtml,
    "about.html": aboutHtml,
    "contact.html": contactHtml,
    "style.css": styleCss
  };
}

app.post("/generate-site", (req, res) => {
  const { template, idea } = req.body || {};
  const pages = buildPages({ template, idea });
  res.json({ pages });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Running on port ${PORT}`);
});
