require("dotenv").config();
const express = require("express");
const path = require("path");
const cors = require("cors");
const JSZip = require("jszip");
const connectDB = require("./db");
const Project = require("./models/Project");

const app = express();

connectDB();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

// Pages
app.get("/", (req, res) => res.sendFile(path.join(__dirname, "public/index.html")));
app.get("/gallery", (req, res) => res.sendFile(path.join(__dirname, "public/gallery.html")));
app.get("/builder", (req, res) => res.sendFile(path.join(__dirname, "public/builder.html")));
app.get("/customize", (req, res) => res.sendFile(path.join(__dirname, "public/customize.html")));
app.get("/review", (req, res) => res.sendFile(path.join(__dirname, "public/review.html")));

// AI: section
app.post("/api/ai/section", (req, res) => {
  const { prompt } = req.body;
  const html = `
<section class="ai-section">
  <h2>${prompt}</h2>
  <p>This section was generated by JDZ AI based on your request.</p>
</section>
  `;
  res.json({ html });
});

// AI: copy
app.post("/api/ai/copy", (req, res) => {
  const { type, topic } = req.body;
  const samples = {
    hero: `Welcome to ${topic}! A bold new presence for your brand.`,
    about: `${topic} is built on passion, clarity, and purpose.`,
    features: `Why ${topic} stands out from the rest.`
  };
  res.json({ text: samples[type] || "Generated copy coming soon." });
});

// Save project
app.post("/api/project/save", async (req, res) => {
  const { template, content, styles } = req.body;
  const project = await Project.create({ template, content, styles });
  res.json({ success: true, id: project._id });
});

// Load project
app.get("/api/project/:id", async (req, res) => {
  const project = await Project.findById(req.params.id);
  res.json(project);
});

// Export HTML
app.post("/api/export/html", (req, res) => {
  const { content, styles } = req.body;
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JDZ Export</title>
  <style>
    body { background:${styles.bg}; color:${styles.text}; font-family:${styles.font}; }
    :root { --accent:${styles.accent}; --radius:${styles.radius}; }
  </style>
</head>
<body>
${content}
</body>
</html>
  `;
  res.setHeader("Content-Disposition", "attachment; filename=jdz-export.html");
  res.send(html);
});

// Export ZIP
app.post("/api/export/zip", async (req, res) => {
  const { content, styles } = req.body;
  const zip = new JSZip();

  zip.file("index.html", `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JDZ Export</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
${content}
</body>
</html>
  `);

  zip.file("styles.css", `
body { background:${styles.bg}; color:${styles.text}; font-family:${styles.font}; }
:root { --accent:${styles.accent}; --radius:${styles.radius}; }
  `);

  const data = await zip.generateAsync({ type: "nodebuffer" });
  res.setHeader("Content-Disposition", "attachment; filename=jdz-site.zip");
  res.send(data);
});

// 404
app.use((req, res) => {
  res.status(404).send(`
    <h1 style="font-family:Arial;padding:40px;">
      404 — Page Not Found<br><br>
      <a href="/" style="color:#00eaff;">Return Home</a>
    </h1>
  `);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`JDZ server running at http://localhost:${PORT}`));
